version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 15

  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 15
