db_tier: db-f1-micro
db_highAvailability: false
db_pointInTimeRecovery: false
db_type: POSTGRES_16
kafkaPool: nav-dev
azureTenant: trygdeetaten.no
cpu: 50m
memory: 512Mi
env:
  SPRING_PROFILES_ACTIVE: default,testdatareset
  KAFKA_KEY_GENERATOR_AAD_CLIENT_ID: dev-gcp.paw.paw-kafka-key-generator
  KAFKA_KEY_GENERATOR_URL: http://paw-kafka-key-generator.paw
  ARBEIDSSOEKERREGISTERET_API_AAD_CLIENT_ID: dev-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag
  ARBEIDSSOEKERREGISTERET_API_URL: http://paw-arbeidssoekerregisteret-api-oppslag.paw