db_tier: db-custom-1-3840
db_highAvailability: true
db_pointInTimeRecovery: true
db_type: POSTGRES_17
kafkaPool: nav-prod
azureTenant: nav.no
cpu: 100m
memory: 768Mi
env:
  SPRING_PROFILES_ACTIVE: default
  KAFKA_KEY_GENERATOR_AAD_CLIENT_ID: prod-gcp.paw.paw-kafka-key-generator
  KAFKA_KEY_GENERATOR_URL: http://paw-kafka-key-generator.paw
  ARBEIDSSOEKERREGISTERET_API_AAD_CLIENT_ID: prod-gcp.paw.paw-arbeidssoekerregisteret-api-oppslag-v2
  ARBEIDSSOEKERREGISTERET_API_URL: http://paw-arbeidssoekerregisteret-api-oppslag-v2.paw