server:
  port: 8080
  shutdown: graceful

spring:
  main.banner-mode: 'off'
  profiles:
    active: default
  flyway:
    enabled: true
  datasource:
    url: "${DB_JDBC_URL}&reWriteBatchedInserts=true"
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

management:
  endpoint:
    health.probes.enabled: true
    prometheus:
      access: read_only
  endpoints.web:
    base-path: "/internal"
    exposure.include: health, prometheus
  health:
    livenessstate.enabled: true
    readinessState.enabled: true
  prometheus:
    metrics.export.enabled: true

logging.config: "classpath:logback.xml"

aiven-kafka:
  auto-offset-reset: none
  security-protocol: SSL